version: '3'

services:
  app:
    image: boilerplate-mern
    environment:
      NODE_APP_INSTANCE: 'docker'
      NODE_CONFIG_ENV: 'e2e'
      NODE_ENV: 'e2e'
    command: 'npm run e2e:ci'
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - './:/app:delegated'
      - '/app/node_modules/'
    working_dir: /app

  db:
    image: mongo:5.0
    ports:
      - '27017:27017'
