accounts:
  tokenKey: 'JWT_TOKEN'
  passwordResetEmailEnabled: 'PASSWORD_RESET_EMAIL_ENABLED'

mailer:
  defaultEmail: 'DEFAULT_EMAIL'
  defaultEmailName: 'DEFAULT_EMAIL_NAME'
  forgetPasswordMailTemplateId: 'FORGOT_PASSWORD_MAIL_TEMPLATE_ID'

rollbar:
  env: 'ROLLBAR_ENV'
  accessToken: 'ROLLBAR_ACCESS_TOKEN'

twilio:
  verify:
    accountSid: 'TWILIO_ACCOUNT_SID'
    authToken: 'TWILIO_AUTH_TOKEN'
  messaging:
    messagingServiceSid: 'TWILIO_MESSAGING_SERVICE_SID'

sendgrid:
  apiKey: 'SENDGRID_API_KEY'

mongoDb:
  uri: 'MONGODB_URI'

server:
  port: 'PORT'

webAppHost: 'WEB_APP_HOST'

inspectlet:
  wid: 'INSPECTLET_KEY'

datadog:
  api_key: 'DD_API_KEY'
  app_name: 'DD_APP_NAME'
