accounts:
  tokenKey: 'JWT_TOKEN'

rollbar:
  env: 'ROLLBAR_ENV'
  accessToken: 'ROLLBAR_ACCESS_TOKEN'

twilio:
  verify:
    accountSid: 'TWILIO_ACCOUNT_SID'
    authToken: 'TWILIO_AUTH_TOKEN'
    verifySid: 'TWILIO_VERIFY_SID'
  messaging:
    messagingServiceSid: 'TWILIO_MESSAGING_SERVICE_SID'

sendgrid:
  apiKey: 'SENDGRID_API_KEY'

mongoDb:
  uri: 'MONGODB_URI'

server:
  port: 'PORT'

webAppHost: 'WEB_APP_HOST'

inspectlet:
  wid: 'INSPECTLET_KEY'

datadog:
  api_key: 'DD_API_KEY'
  app_name: 'DD_APP_NAME'
