accounts:
  tokenKey: 'JWT_TOKEN'

datadog:
  api_key: 'DD_API_KEY'
  app_name: 'DD_APP_NAME'

inspectlet:
  wid: 'INSPECTLET_KEY'

mailer:
  defaultEmail: 'DEFAULT_EMAIL'
  defaultEmailName: 'DEFAULT_EMAIL_NAME'
  forgetPasswordMailTemplateId: 'FORGOT_PASSWORD_MAIL_TEMPLATE_ID'

mongoDb:
  uri: 'MONGODB_URI'

otp:
  defaultOTP: 'DEFAULT_OTP'
  defaultPhoneNumber: 'DEFAULT_PHONE_NUMBER'

rollbar:
  env: 'ROLLBAR_ENV'
  accessToken: 'ROLLBAR_ACCESS_TOKEN'

sendgrid:
  apiKey: 'SENDGRID_API_KEY'

server:
  port: 'PORT'

twilio:
  verify:
    accountSid: 'TWILIO_ACCOUNT_SID'
    authToken: 'TWILIO_AUTH_TOKEN'
  messaging:
    messagingServiceSid: 'TWILIO_MESSAGING_SERVICE_SID'

webAppHost: 'WEB_APP_HOST'
