webAppHost: 'http://localhost:8080'

jwt:
  token: 'dev_auth_token'

mongoDb:
  uri: 'mongodb://localhost:27017/boilerplate-mern-dev'

grafana:
  labels:
    env: 'development'

public:
  env: 'development'
