accounts:
  tokenKey: 'test_auth_token'

mongoDb:
  uri: 'mongodb://localhost:27017/boilerplate-mern-test'

test:
  boolTestKey: true
  numberTestKey: 1
  stringTestKey: 'string'

webAppHost: 'http://localhost:8080'
