boolTestKey: true
numberTestKey: 1
stringTestKey: 'string'

rollbar:
  accessToken: 'ROLLBAR_ACCESS_TOKEN'
  env: 'ROLLBAR_ENV'

jwt:
  token: 'JWT_TOKEN'

communication:
  services: ['twilio', 'sendgrid']
  mock: false

twilio:
  verify:
    accountSid: 'AC.TWILIO_ACCOUNT_SID'
    authToken: 'TWILIO_AUTH_TOKEN'
  messaging:
    messagingServiceSid: 'TWILIO_MESSAGING_SERVICE_SID'

sendgridApiKey: 'SG.SENDGRID_API_KEY'

mongoDb:
  uri: 'mongodb://localhost:27017/boilerplate-mern-test'

server:
  port: '8080'
