name: clean_on_delete

on: delete

jobs:
  clean:
    # only run when deleting a branch
    if: github.event.ref_type == 'branch'
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@v1.0
    concurrency:
      group: ci-preview-${{ github.event.ref }}
      cancel-in-progress: true
    with:
      app_name: boilerplate-mern
      app_env: preview
      branch: ${{ github.event.ref }}
      deploy_service: digitalocean-kube
    secrets:
      docker_registry: docker-registry.platform.jalantechnologies.com/boilerplate-mern
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}
