name: clean_on_pr_closed

on:
  pull_request_target:
    types:
      - closed

jobs:
  clean:
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@v2.4
    concurrency:
      group: ci-preview-${{ github.event.pull_request.head.ref }}
      cancel-in-progress: true
    with:
      app_name: boilerplate-mern
      app_env: preview
      branch: ${{ github.event.pull_request.head.ref }}
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
