name: preview_on_dispatch

on: workflow_dispatch

jobs:
  preview:
    uses: jalantechnologies/platform-github/.github/workflows/kube.yml@v2.2
    with:
      app_name: boilerplate-mern
      app_env: preview
      app_hostname: '{1}.preview.platform.jalantechnologies.com'
      branch: ${{ github.event.ref }}
      steps: 'preview'
    secrets:
      docker_registry: docker-registry.platform.jalantechnologies.com/boilerplate-mern
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      doppler_token: ${{ secrets.DOPPLER_PREVIEW_TOKEN }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}
